<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class parts extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('materials')->insert([
            ['part_name' => 'LUMP COVER X80','model_no' =>3],
            ['part_name' => 'OUTER BOX','model_no' =>3],
            ['part_name' => 'NEON SWITCH B','model_no' =>10],
            ['part_name' => 'BODY 026  WHITE','model_no' =>477],
            ['part_name' => 'COVER 022 WHITE','model_no' =>477],
            ['part_name' => 'INNER BOX','model_no' =>477],
            ['part_name' => '16 BLADE BLOCK','model_no' =>469],
            ['part_name' => 'COVER PLATE 065 SILVER ASSY','model_no' =>395],
            ['part_name' => 'COVER PLATE 065 SILVER ASSY','model_no' =>333],
            ['part_name' => 'SECREW 620','model_no' =>395],
            ['part_name' => 'SECREW 620','model_no' =>333],
            ['part_name' => 'COVER PLATE Y05 SILVER','model_no' =>398],
            ['part_name' => 'COVER PLATE Y05 SILVER','model_no' =>336],
            ['part_name' => 'SWITCH 1D 1G 2W','model_no' =>164],
            ['part_name' => 'SWITCH 1D 1G 2W','model_no' =>143],
            ['part_name' => 'BODY 3010-N','model_no' =>168],
            ['part_name' => 'BODY 3010-N','model_no' =>147],
            ['part_name' => 'COVER N61 GRAY','model_no' =>431],
            ['part_name' => 'COVER N61 GRAY','model_no' =>369],
            ['part_name' => 'SECREW 620','model_no' =>431],
            ['part_name' => 'SECREW 620','model_no' =>369],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>437],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>375],
            ['part_name' => 'COVER N61 GREY','model_no' =>437],
            ['part_name' => 'COVER N61 GREY','model_no' =>375],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>443],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>381],
            ['part_name' => 'SCREW 620','model_no' =>443],
            ['part_name' => 'SCREW 620','model_no' =>381],
            ['part_name' => 'COVER N61 ASSY','model_no' =>443],
            ['part_name' => 'COVER N61 ASSY','model_no' =>381],
            ['part_name' => 'BASE PLATE 1G_BLANK PLATE','model_no' =>159],
            ['part_name' => 'BASE PLATE 1G_BLANK PLATE','model_no' =>138],
            ['part_name' => 'SWITCH 1G-1D-1W','model_no' =>159],
            ['part_name' => 'SWITCH 1G-1D-1W','model_no' =>138],
            ['part_name' => 'BASE PLATE 2D','model_no' =>161],
            ['part_name' => 'BASE PLATE 2D','model_no' =>140],
            ['part_name' => 'SWITCH 1D 1G 2W','model_no' =>161],
            ['part_name' => 'SWITCH 1D 1G 2W','model_no' =>140],
            ['part_name' => 'BASE PLATE 3D','model_no' =>163],
            ['part_name' => 'BASE PLATE 3D','model_no' =>142],
            ['part_name' => 'SWITCH 1D 1G 3W','model_no' =>163],
            ['part_name' => 'SWITCH 1D 1G 3W','model_no' =>142],
            ['part_name' => 'USB  WEF1172H','model_no' =>231],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>429],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>367],
            ['part_name' => 'COVER N61 ASSY','model_no' =>429],
            ['part_name' => 'COVER N61 ASSY','model_no' =>367],
            ['part_name' => 'SECREW 620','model_no' =>429],
            ['part_name' => 'SECREW 620','model_no' =>367],
            ['part_name' => 'COVER PLATE Q78 PASTEL PINK','model_no' =>429],
            ['part_name' => 'COVER PLATE Q78 PASTEL PINK','model_no' =>367],
            ['part_name' => 'HANDLE 837','model_no' =>45],
            ['part_name' => 'HANDLE 837','model_no' =>46],
            ['part_name' => 'TERMINAL 16','model_no' =>471],
            ['part_name' => 'TERMINAL 17','model_no' =>471],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>422],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>360],
            ['part_name' => 'SCREW 620','model_no' =>422],
            ['part_name' => 'SCREW 620','model_no' =>360],
            ['part_name' => 'COVER N61 ASSY','model_no' =>422],
            ['part_name' => 'COVER N61 ASSY','model_no' =>360],
            ['part_name' => 'COVER PLATE 066 W','model_no' =>394],
            ['part_name' => 'COVER PLATE 066 W','model_no' =>332],
            ['part_name' => 'SCREW 620','model_no' =>394],
            ['part_name' => 'SCREW 620','model_no' =>332],
            ['part_name' => 'ASS GANG CAT 6 RJ45','model_no' =>170],
            ['part_name' => 'ASS GANG CAT 6 RJ45','model_no' =>149],
            ['part_name' => 'HANDLE 837','model_no' =>55],
            ['part_name' => 'OUTER BOX','model_no' =>55],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>426],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>364],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>449],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>387],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>448],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>386],
            ['part_name' => 'SCREW 620','model_no' =>448],
            ['part_name' => 'SCREW 620','model_no' =>386],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>447],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>385],
            ['part_name' => 'OUTER BOX','model_no' =>37],
            ['part_name' => 'HANDLE 837','model_no' =>37],
            ['part_name' => 'COVER PLATE YO5 WHITE','model_no' =>397],
            ['part_name' => 'COVER PLATE YO5 WHITE','model_no' =>335],
            ['part_name' => 'HANDLE 837','model_no' =>6],
            ['part_name' => 'OUTER BOX','model_no' =>402],
            ['part_name' => 'OUTER BOX','model_no' =>340],
            ['part_name' => 'COVER PLATE 066 B','model_no' =>402],
            ['part_name' => 'COVER PLATE 066 B','model_no' =>340],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>402],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>340],
            ['part_name' => 'BODY BLOCK STYLE 1121','model_no' =>393],
            ['part_name' => 'BODY BLOCK STYLE 1121','model_no' =>331],
            ['part_name' => 'SCREW 620','model_no' =>393],
            ['part_name' => 'SCREW 620','model_no' =>331],
            ['part_name' => 'COVER PLATE 066 SILVER SPRAY','model_no' =>393],
            ['part_name' => 'COVER PLATE 066 SILVER SPRAY','model_no' =>331],
            ['part_name' => 'OUTER BOX','model_no' =>393],
            ['part_name' => 'OUTER BOX','model_no' =>331],
            ['part_name' => 'BODY 032','model_no' =>153],
            ['part_name' => 'BODY 032','model_no' =>132],
            ['part_name' => 'BODY 032','model_no' =>58],
            ['part_name' => 'SWITCH BLOCK','model_no' =>200],
            ['part_name' => 'SWITCH PLATE','model_no' =>200],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>200],
            ['part_name' => 'SWITCH BLOCK','model_no' =>201],
            ['part_name' => 'SWITCH PLATE','model_no' =>201],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>201],
            ['part_name' => 'SWITCH BLOCK','model_no' =>214],
            ['part_name' => 'SWITCH PLATE','model_no' =>214],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>214],
            ['part_name' => 'SWITCH BLOCK','model_no' =>310],
            ['part_name' => 'SWITCH PLATE','model_no' =>310],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>310],
            ['part_name' => 'SWITCH BLOCK','model_no' =>312],
            ['part_name' => 'SWITCH PLATE','model_no' =>312],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>312],
            ['part_name' => 'COVER','model_no' =>309],
            ['part_name' => 'PLATE','model_no' =>309],
            ['part_name' => 'COVER PLATE','model_no' =>308],
            ['part_name' => 'SWITCH SUPPORT','model_no' =>308],
            ['part_name' => 'BODY BLOCK R 25','model_no' =>212],
            ['part_name' => 'COVER PLATE 064 W','model_no' =>212],
            ['part_name' => 'COVER N61 GREY','model_no' =>430],
            ['part_name' => 'COVER N61 GREY','model_no' =>368],
            ['part_name' => 'PLATE Q78 BROWN METALIC','model_no' =>430],
            ['part_name' => 'PLATE Q78 BROWN METALIC','model_no' =>368],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>427],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>365],
            ['part_name' => 'COVER PLATE Q78 GOLD METALIC','model_no' =>427],
            ['part_name' => 'COVER PLATE Q78 GOLD METALIC','model_no' =>365],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>427],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>365],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>428],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>366],
            ['part_name' => 'COVER N61 ASSY','model_no' =>428],
            ['part_name' => 'COVER N61 ASSY','model_no' =>366],
            ['part_name' => 'COVER PLATE Q78 BLUE','model_no' =>428],
            ['part_name' => 'COVER PLATE Q78 BLUE','model_no' =>366],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>434],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>372],
            ['part_name' => 'COVER N61 ASSY','model_no' =>434],
            ['part_name' => 'COVER N61 ASSY','model_no' =>372],
            ['part_name' => 'COVER PLATE Q82 BLUE','model_no' =>434],
            ['part_name' => 'COVER PLATE Q82 BLUE','model_no' =>372],
            ['part_name' => 'BODY R26','model_no' =>416],
            ['part_name' => 'BODY R26','model_no' =>354],
            ['part_name' => 'SCREW 620','model_no' =>416],
            ['part_name' => 'SCREW 620','model_no' =>354],
            ['part_name' => 'BODY BLOCK R26','model_no' =>415],
            ['part_name' => 'BODY BLOCK R26','model_no' =>353],
            ['part_name' => 'SCREW 620','model_no' =>415],
            ['part_name' => 'SCREW 620','model_no' =>353],
            ['part_name' => 'OUTER BOX','model_no' =>415],
            ['part_name' => 'OUTER BOX','model_no' =>353],
            ['part_name' => 'MOUNTING STRAP','model_no' =>184],
            ['part_name' => 'MODERN PLATE','model_no' =>199],
            ['part_name' => 'PLATE WNJ 6009','model_no' =>195],
            ['part_name' => 'PLATE WNJ6012','model_no' =>205],
            ['part_name' => 'USB WEF1172W','model_no' =>208],
            ['part_name' => 'BODY BLOCK WNTJ15649W','model_no' =>233],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>25],
            ['part_name' => 'COVER M64','model_no' =>27],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>27],
            ['part_name' => 'OUTER BOX','model_no' =>27],
            ['part_name' => 'OUTER BOX','model_no' =>28],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>28],
            ['part_name' => 'COVER M64','model_no' =>28],
            ['part_name' => 'HANDLE 837','model_no' =>41],
            ['part_name' => 'BODY BLOCK R26','model_no' =>414],
            ['part_name' => 'BODY BLOCK R26','model_no' =>352],
            ['part_name' => 'SCREW 620','model_no' =>414],
            ['part_name' => 'SCREW 620','model_no' =>352],
            ['part_name' => 'HANDLE 837','model_no' =>15],
            ['part_name' => 'OUTER BOX','model_no' =>32],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>34],
            ['part_name' => 'OUTER BOX','model_no' =>34],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>426],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>364],
            ['part_name' => 'COVER PLATE Q78 SILVER METALIC','model_no' =>426],
            ['part_name' => 'COVER PLATE Q78 SILVER METALIC','model_no' =>364],
            ['part_name' => 'OUTER BOX','model_no' =>29],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>29],
            ['part_name' => 'OUTER BOX','model_no' =>30],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>30],
            ['part_name' => 'OUTER BOX','model_no' =>31],
            ['part_name' => 'NEON SWITCH C  ASSY','model_no' =>31],
            ['part_name' => 'SCREW 620','model_no' =>400],
            ['part_name' => 'SCREW 620','model_no' =>338],
            ['part_name' => 'COVER PLATE Y03 BLACK SPRAY','model_no' =>400],
            ['part_name' => 'COVER PLATE Y03 BLACK SPRAY','model_no' =>338],
            ['part_name' => 'HANDLE 837','model_no' =>32],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>2],
            ['part_name' => 'COVER PLATE Y04 SILVER ASSY','model_no' =>392],
            ['part_name' => 'COVER PLATE Y04 SILVER ASSY','model_no' =>330],
            ['part_name' => 'BODY R26','model_no' =>417],
            ['part_name' => 'BODY R26','model_no' =>355],
            ['part_name' => 'SCREW 620','model_no' =>417],
            ['part_name' => 'SCREW 620','model_no' =>355],
            ['part_name' => 'BODY R25','model_no' =>417],
            ['part_name' => 'BODY R25','model_no' =>355],
            ['part_name' => 'BODY BLOCK R26','model_no' =>417],
            ['part_name' => 'BODY BLOCK R26','model_no' =>355],
            ['part_name' => 'BODY 026  WHITE','model_no' =>473],
            ['part_name' => 'COVER 021 WHITE','model_no' =>473],
            ['part_name' => 'SCREW 18','model_no' =>473],
            ['part_name' => 'OUTER BOX','model_no' =>473],
            ['part_name' => 'COVER 021 WHITE','model_no' =>474],
            ['part_name' => 'INNER BOX','model_no' =>474],
            ['part_name' => 'COVER PLATE 065 W','model_no' =>396],
            ['part_name' => 'COVER PLATE 065 W','model_no' =>334],
            ['part_name' => 'NEON SWITCH B','model_no' =>8],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>438],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>376],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>438],
            ['part_name' => 'COVER N61 ASSY GREY','model_no' =>376],
            ['part_name' => 'SCREW 620','model_no' =>451],
            ['part_name' => 'SCREW 620','model_no' =>389],
            ['part_name' => 'COVER N61 GRAY','model_no' =>451],
            ['part_name' => 'COVER N61 GRAY','model_no' =>389],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>451],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>389],
            ['part_name' => 'COVER PLATE T89 MAROON METALIC','model_no' =>451],
            ['part_name' => 'COVER PLATE T89 MAROON METALIC','model_no' =>389],
            ['part_name' => 'BODY BLOCK','model_no' =>190],
            ['part_name' => 'COVER BLOCK','model_no' =>190],
            ['part_name' => 'MANUAL INSTRUCTION','model_no' =>190],
            ['part_name' => '16 BLADE BLOCK','model_no' =>470],
            ['part_name' => '17 BLADE BLOCK','model_no' =>470],
            ['part_name' => 'OUTER WH2013BP','model_no' =>478],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>432],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>370],
            ['part_name' => 'COVER N61 GRAY','model_no' =>432],
            ['part_name' => 'COVER N61 GRAY','model_no' =>370],
            ['part_name' => 'OUTER BOX','model_no' =>168],
            ['part_name' => 'OUTER BOX','model_no' =>147],
            ['part_name' => 'BLANK PLATE','model_no' =>173],
            ['part_name' => 'BLANK PLATE','model_no' =>152],
            ['part_name' => 'OUTER BOX','model_no' =>173],
            ['part_name' => 'OUTER BOX','model_no' =>152],
            ['part_name' => 'BLANK CHIP WEJ3020H GREY','model_no' =>186],
            ['part_name' => 'BODY N54','model_no' =>193],
            ['part_name' => 'OBOX WNJ','model_no' =>241],
            ['part_name' => 'BODY  BLOCK 57591','model_no' =>207],
            ['part_name' => 'INNER WH2012','model_no' =>473],
            ['part_name' => 'SCREW 620','model_no' =>409],
            ['part_name' => 'SCREW 620','model_no' =>347],
            ['part_name' => 'BODY BLOCK R26','model_no' =>409],
            ['part_name' => 'BODY BLOCK R26','model_no' =>347],
            ['part_name' => 'PLATE Y03 W','model_no' =>409],
            ['part_name' => 'PLATE Y03 W','model_no' =>347],
            ['part_name' => 'COVER PLATE 105','model_no' =>157],
            ['part_name' => 'COVER PLATE 105','model_no' =>136],
            ['part_name' => 'OUTER BOX WCJP 2164','model_no' =>157],
            ['part_name' => 'OUTER BOX WCJP 2164','model_no' =>136],
            ['part_name' => 'OUTBOW AC CONCENT WBJ 6010W','model_no' =>188],
            ['part_name' => 'COVER PLATE 064 BLACK','model_no' =>317],
            ['part_name' => 'COVER PLATE 105','model_no' =>158],
            ['part_name' => 'COVER PLATE 105','model_no' =>137],
            ['part_name' => 'SCREW 855','model_no' =>158],
            ['part_name' => 'SCREW 855','model_no' =>137],
            ['part_name' => 'WEJ 2488','model_no' =>158],
            ['part_name' => 'WEJ 2488','model_no' =>137],
            ['part_name' => 'INNER BOX','model_no' =>191],
            ['part_name' => 'BODY BLOCK DIMMER','model_no' =>191],
            ['part_name' => 'MOUNTING P 74','model_no' =>158],
            ['part_name' => 'MOUNTING P 74','model_no' =>137],
            ['part_name' => 'PLATE COVER YO3 AS','model_no' =>414],
            ['part_name' => 'PLATE COVER YO3 AS','model_no' =>352],
            ['part_name' => 'OUTER BOX','model_no' =>213],
            ['part_name' => 'INNER BOX','model_no' =>213],
            ['part_name' => 'BODY 026B','model_no' =>475],
            ['part_name' => 'COVER 021B','model_no' =>475],
            ['part_name' => 'TERMINAL 18','model_no' =>475],
            ['part_name' => 'SCREW 018','model_no' =>475],
            ['part_name' => 'INNER WH2012BP','model_no' =>475],
            ['part_name' => 'OUTER WH2012BP','model_no' =>475],
            ['part_name' => 'PLATE WNJ 6891','model_no' =>240],
            ['part_name' => 'OUTER BOX','model_no' =>202],
            ['part_name' => '16 BLADE BLOCK','model_no' =>472],
            ['part_name' => '17 BLADE BLOCK','model_no' =>472],
            ['part_name' => '221 BODY BLACK','model_no' =>472],
            ['part_name' => '177 COVER BLACK','model_no' =>472],
            ['part_name' => '015 TERMINAL SCREW','model_no' =>472],
            ['part_name' => '143 PAN HEAD SCREW','model_no' =>472],
            ['part_name' => 'OUTER WH2012PK','model_no' =>474],
            ['part_name' => 'COVER PLATE Y04AS','model_no' =>416],
            ['part_name' => 'COVER PLATE Y04AS','model_no' =>354],
            ['part_name' => 'OUTER BOX','model_no' =>416],
            ['part_name' => 'OUTER BOX','model_no' =>354],
            ['part_name' => 'NEON SWITCH B','model_no' =>4],
            ['part_name' => 'BODY R25','model_no' =>320],
            ['part_name' => 'PLATE WESJ 78019CW','model_no' =>320],
            ['part_name' => 'HANDLE 837','model_no' =>16],
            ['part_name' => 'COVER M64','model_no' =>16],
            ['part_name' => 'OUTER BOX','model_no' =>8],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>1],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>423],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>361],
            ['part_name' => 'COVER PLATE Q78 GREEN','model_no' =>423],
            ['part_name' => 'COVER PLATE Q78 GREEN','model_no' =>361],
            ['part_name' => 'COVER N61 ASSY','model_no' =>423],
            ['part_name' => 'COVER N61 ASSY','model_no' =>361],
            ['part_name' => '148 SOCKET CONTACT BLOCK','model_no' =>477],
            ['part_name' => 'MOUNTING P 74','model_no' =>156],
            ['part_name' => 'MOUNTING P 74','model_no' =>135],
            ['part_name' => 'BACK PIECE GERMAN','model_no' =>166],
            ['part_name' => 'BACK PIECE GERMAN','model_no' =>145],
            ['part_name' => 'BASE  PLATE COVER','model_no' =>166],
            ['part_name' => 'BASE  PLATE COVER','model_no' =>145],
            ['part_name' => 'DU69JTK1','model_no' =>177],
            ['part_name' => 'OUTER BOX','model_no' =>56],
            ['part_name' => 'INNER BOX','model_no' =>56],
            ['part_name' => 'BODY P27','model_no' =>56],
            ['part_name' => 'COVER PLATE 105','model_no' =>156],
            ['part_name' => 'COVER PLATE 105','model_no' =>135],
            ['part_name' => 'SCREW 855','model_no' =>156],
            ['part_name' => 'SCREW 855','model_no' =>135],
            ['part_name' => 'MOUNTING P 74','model_no' =>157],
            ['part_name' => 'MOUNTING P 74','model_no' =>136],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>444],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>382],
            ['part_name' => 'SCREW 620','model_no' =>444],
            ['part_name' => 'SCREW 620','model_no' =>382],
            ['part_name' => 'COVER N61 ASSY','model_no' =>444],
            ['part_name' => 'COVER N61 ASSY','model_no' =>382],
            ['part_name' => 'COVER PLATE T89','model_no' =>444],
            ['part_name' => 'COVER PLATE T89','model_no' =>382],
            ['part_name' => 'COVER PLATE T89','model_no' =>443],
            ['part_name' => 'COVER PLATE T89','model_no' =>381],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>442],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>380],
            ['part_name' => 'SCREW 620','model_no' =>442],
            ['part_name' => 'SCREW 620','model_no' =>380],
            ['part_name' => 'COVER N61 ASSY','model_no' =>442],
            ['part_name' => 'COVER N61 ASSY','model_no' =>380],
            ['part_name' => 'COVER PLATE T89','model_no' =>442],
            ['part_name' => 'COVER PLATE T89','model_no' =>380],
            ['part_name' => 'SPRING R76','model_no' =>192],
            ['part_name' => 'BODY BLOCK NRJ3160W','model_no' =>235],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>12],
            ['part_name' => 'COVER M64','model_no' =>12],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>52],
            ['part_name' => 'COVER M64','model_no' =>52],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>11],
            ['part_name' => 'OUTER BOX','model_no' =>11],
            ['part_name' => 'Y07 PLATE DARK GRAY','model_no' =>419],
            ['part_name' => 'Y07 PLATE DARK GRAY','model_no' =>357],
            ['part_name' => 'SCREW 620','model_no' =>419],
            ['part_name' => 'SCREW 620','model_no' =>357],
            ['part_name' => 'SCREW 620','model_no' =>424],
            ['part_name' => 'SCREW 620','model_no' =>362],
            ['part_name' => 'NEON SWITCH B STYLE E','model_no' =>3],
            ['part_name' => 'C0VER PLATE 064 SILVER','model_no' =>211],
            ['part_name' => 'COVER N61 GRAY','model_no' =>449],
            ['part_name' => 'COVER N61 GRAY','model_no' =>387],
            ['part_name' => 'DUMF3230J1','model_no' =>180],
            ['part_name' => 'WZJ11217W268','model_no' =>180],
            ['part_name' => 'COVER PLATE 065 BLACK ASSY','model_no' =>403],
            ['part_name' => 'COVER PLATE 065 BLACK ASSY','model_no' =>341],
            ['part_name' => 'SCREW 855','model_no' =>154],
            ['part_name' => 'SCREW 855','model_no' =>133],
            ['part_name' => 'SCREW 855','model_no' =>59],
            ['part_name' => 'BODY 032','model_no' =>154],
            ['part_name' => 'BODY 032','model_no' =>133],
            ['part_name' => 'BODY 032','model_no' =>59],
            ['part_name' => 'BODY 093','model_no' =>154],
            ['part_name' => 'BODY 093','model_no' =>133],
            ['part_name' => 'BODY 093','model_no' =>59],
            ['part_name' => 'HANDLE 926','model_no' =>154],
            ['part_name' => 'HANDLE 926','model_no' =>133],
            ['part_name' => 'HANDLE 926','model_no' =>59],
            ['part_name' => 'COVER PLATE 096','model_no' =>155],
            ['part_name' => 'COVER PLATE 096','model_no' =>134],
            ['part_name' => 'COVER X16','model_no' =>154],
            ['part_name' => 'COVER X16','model_no' =>133],
            ['part_name' => 'COVER X16','model_no' =>59],
            ['part_name' => 'COVER M64','model_no' =>49],
            ['part_name' => 'HANDLE 837','model_no' =>49],
            ['part_name' => 'HANDLE 927','model_no' =>153],
            ['part_name' => 'HANDLE 927','model_no' =>132],
            ['part_name' => 'HANDLE 927','model_no' =>58],
            ['part_name' => 'OUTER BOX','model_no' =>53],
            ['part_name' => 'INNER BOX','model_no' =>53],
            ['part_name' => 'HANDLE 837','model_no' =>53],
            ['part_name' => 'OUTER BOX','model_no' =>153],
            ['part_name' => 'OUTER BOX','model_no' =>132],
            ['part_name' => 'OUTER BOX','model_no' =>58],
            ['part_name' => 'SWITCH ASEMBLY 20A DP BS SERIES','model_no' =>160],
            ['part_name' => 'SWITCH ASEMBLY 20A DP BS SERIES','model_no' =>139],
            ['part_name' => 'BASE PLATE','model_no' =>160],
            ['part_name' => 'BASE PLATE','model_no' =>139],
            ['part_name' => 'SWITCH ASSEMBLY 1G 1D 2WSP 10AX','model_no' =>162],
            ['part_name' => 'SWITCH ASSEMBLY 1G 1D 2WSP 10AX','model_no' =>141],
            ['part_name' => 'BASE PLATE 1D','model_no' =>171],
            ['part_name' => 'BASE PLATE 1D','model_no' =>150],
            ['part_name' => 'SHUTTER RETAINIR','model_no' =>166],
            ['part_name' => 'SHUTTER RETAINIR','model_no' =>145],
            ['part_name' => 'FAMALE CONTACK 750','model_no' =>166],
            ['part_name' => 'FAMALE CONTACK 750','model_no' =>145],
            ['part_name' => 'FAMALE CONTACK 751','model_no' =>166],
            ['part_name' => 'FAMALE CONTACK 751','model_no' =>145],
            ['part_name' => 'DU69JTK-1','model_no' =>179],
            ['part_name' => 'WEJ 3020','model_no' =>179],
            ['part_name' => 'WEJ 2488','model_no' =>179],
            ['part_name' => 'DU69JTK-1','model_no' =>178],
            ['part_name' => 'WEJ 3020','model_no' =>178],
            ['part_name' => 'MOUNTING P74','model_no' =>155],
            ['part_name' => 'MOUNTING P74','model_no' =>134],
            ['part_name' => '177 COVER WHITE','model_no' =>470],
            ['part_name' => 'COVER 097','model_no' =>155],
            ['part_name' => 'COVER 097','model_no' =>134],
            ['part_name' => 'INNER  WEJ 5571','model_no' =>4],
            ['part_name' => 'OUTER WEJ 5571','model_no' =>4],
            ['part_name' => 'INNER BLANK','model_no' =>180],
            ['part_name' => 'HANDLE 837','model_no' =>14],
            ['part_name' => 'COVER M64','model_no' =>3],
            ['part_name' => 'BODY BLOCK','model_no' =>198],
            ['part_name' => 'LUMP COVER X82','model_no' =>12],
            ['part_name' => 'OUTER BOX','model_no' =>12],
            ['part_name' => 'OUTER BOX','model_no' =>9],
            ['part_name' => 'NEON SWITCH B ASSY','model_no' =>9],
            ['part_name' => 'TERMINAL18','model_no' =>474],
            ['part_name' => 'BODY BLOCK 277794','model_no' =>206],
            ['part_name' => 'BODY 026 WHITE','model_no' =>474],
            ['part_name' => 'SCREW 18','model_no' =>474],
            ['part_name' => 'OUTER BOX','model_no' =>22],
            ['part_name' => 'HANDLE 837','model_no' =>22],
            ['part_name' => 'HANDLE 837','model_no' =>5],
            ['part_name' => 'NEON SWITCH B','model_no' =>5],
            ['part_name' => 'COVER PLATE Y04 BLACK','model_no' =>401],
            ['part_name' => 'COVER PLATE Y04 BLACK','model_no' =>339],
            ['part_name' => 'BODY R25','model_no' =>236],
            ['part_name' => 'BODY R25','model_no' =>322],
            ['part_name' => 'SCREW 143','model_no' =>470],
            ['part_name' => 'COVER PLATE Y04 WHITE','model_no' =>391],
            ['part_name' => 'COVER PLATE Y04 WHITE','model_no' =>329],
            ['part_name' => '018 PANHEAD SCREW','model_no' =>477],
            ['part_name' => 'HANDLE 837','model_no' =>18],
            ['part_name' => 'OUTER BOX','model_no' =>18],
            ['part_name' => 'HANDLE 837','model_no' =>20],
            ['part_name' => 'HANDLE 837','model_no' =>23],
            ['part_name' => 'OUTER BOX','model_no' =>23],
            ['part_name' => 'HANDLE LINE Q77 GRAY','model_no' =>23],
            ['part_name' => 'COVER M64','model_no' =>38],
            ['part_name' => 'HANDLE 837','model_no' =>17],
            ['part_name' => 'LUMP COVER X80','model_no' =>2],
            ['part_name' => 'HANDLE 837','model_no' =>44],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>436],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>374],
            ['part_name' => 'SCREW 620','model_no' =>436],
            ['part_name' => 'SCREW 620','model_no' =>374],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>425],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>363],
            ['part_name' => 'DUMF3233J1','model_no' =>181],
            ['part_name' => 'WZJ8WZJ1121','model_no' =>181],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>446],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>384],
            ['part_name' => 'COVER W55','model_no' =>425],
            ['part_name' => 'COVER W55','model_no' =>363],
            ['part_name' => 'HANDLE 837','model_no' =>11],
            ['part_name' => 'NEON SWITCH B STILE E','model_no' =>5],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>435],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>373],
            ['part_name' => 'COVER N61','model_no' =>435],
            ['part_name' => 'COVER N61','model_no' =>373],
            ['part_name' => 'OUTER BOX','model_no' =>435],
            ['part_name' => 'OUTER BOX','model_no' =>373],
            ['part_name' => 'OUTER BOX WEHJ 5511','model_no' =>7],
            ['part_name' => 'BODY P27','model_no' =>4],
            ['part_name' => 'COVER M64','model_no' =>4],
            ['part_name' => 'TERMINAL 365','model_no' =>4],
            ['part_name' => 'L83','model_no' =>4],
            ['part_name' => 'L84','model_no' =>4],
            ['part_name' => '555','model_no' =>4],
            ['part_name' => 'BODY N54','model_no' =>192],
            ['part_name' => 'MODULLAR 60838','model_no' =>192],
            ['part_name' => 'OUTER BOX','model_no' =>395],
            ['part_name' => 'OUTER BOX','model_no' =>333],
            ['part_name' => 'FULL COLOR EBG 888','model_no' =>202],
            ['part_name' => 'COVER M64','model_no' =>15],
            ['part_name' => 'HANDLE 837','model_no' =>51],
            ['part_name' => 'OUTER BOX','model_no' =>205],
            ['part_name' => 'BODY BLOCK','model_no' =>191],
            ['part_name' => 'HANDLE 837','model_no' =>43],
            ['part_name' => '17 BLADE BLOCK','model_no' =>469],
            ['part_name' => '015 TERMINAL SCREW','model_no' =>469],
            ['part_name' => '143 PAN HEAD SCREW','model_no' =>469],
            ['part_name' => 'COVER M64','model_no' =>17],
            ['part_name' => 'BODY BLOCK STYLE E+956(1121=7)','model_no' =>403],
            ['part_name' => 'BODY BLOCK STYLE E+956(1121=7)','model_no' =>341],
            ['part_name' => 'OUTER BOX WESJP 11223','model_no' =>403],
            ['part_name' => 'OUTER BOX WESJP 11223','model_no' =>341],
            ['part_name' => 'MODULLAR 60838','model_no' =>194],
            ['part_name' => 'HANDLE 837','model_no' =>54],
            ['part_name' => 'COVER M64','model_no' =>22],
            ['part_name' => 'INNER BOX WH4021BP','model_no' =>472],
            ['part_name' => '221 BODY BLACK','model_no' =>471],
            ['part_name' => '177 COVER BLACK','model_no' =>471],
            ['part_name' => '026 ROTATING PIECE BLACK','model_no' =>471],
            ['part_name' => '015 TERMINAL SCREW','model_no' =>471],
            ['part_name' => '143 PAN HEAD SCREW','model_no' =>471],
            ['part_name' => 'COVER S64','model_no' =>183],
            ['part_name' => '379 HEXAGON NUT','model_no' =>471],
            ['part_name' => 'COVER M64','model_no' =>18],
            ['part_name' => 'HANDLE 837','model_no' =>50],
            ['part_name' => 'COVER M64','model_no' =>48],
            ['part_name' => 'HANDLE 837','model_no' =>48],
            ['part_name' => 'COVER M64','model_no' =>47],
            ['part_name' => 'HANDLE 837','model_no' =>47],
            ['part_name' => 'NEON SWITCH C STYLE','model_no' =>47],
            ['part_name' => 'BODY R26','model_no' =>394],
            ['part_name' => 'BODY R26','model_no' =>332],
            ['part_name' => 'INNER BOX WH4021B','model_no' =>471],
            ['part_name' => 'OUTER BOX WH4021B','model_no' =>471],
            ['part_name' => 'LAYER','model_no' =>190],
            ['part_name' => 'HANDLE 837','model_no' =>25],
            ['part_name' => 'OUTER BOX WH4021WP','model_no' =>470],
            ['part_name' => 'COVER M64','model_no' =>46],
            ['part_name' => 'COVER M64','model_no' =>21],
            ['part_name' => 'HANDLE 837','model_no' =>21],
            ['part_name' => 'COVER M64','model_no' =>20],
            ['part_name' => 'COVER M64','model_no' =>8],
            ['part_name' => 'BLANK CHIP 600M72 1240N','model_no' =>189],
            ['part_name' => 'HANDLE 837','model_no' =>7],
            ['part_name' => 'COVER M64','model_no' =>7],
            ['part_name' => 'COVER M64','model_no' =>10],
            ['part_name' => 'COVER M64','model_no' =>6],
            ['part_name' => 'OUTER BOX','model_no' =>188],
            ['part_name' => 'OUTER BOX','model_no' =>190],
            ['part_name' => 'OUTER BOX WH4021W','model_no' =>469],
            ['part_name' => '177 COVER WHITE','model_no' =>469],
            ['part_name' => 'COVER PLATE  Y05 BLACK ASSY','model_no' =>399],
            ['part_name' => 'COVER PLATE  Y05 BLACK ASSY','model_no' =>337],
            ['part_name' => 'DU 59 JTK','model_no' =>174],
            ['part_name' => 'INNER','model_no' =>174],
            ['part_name' => 'OUTER BOX','model_no' =>433],
            ['part_name' => 'OUTER BOX','model_no' =>371],
            ['part_name' => 'PLATE T89 GREEN','model_no' =>433],
            ['part_name' => 'PLATE T89 GREEN','model_no' =>371],
            ['part_name' => 'DU59JTK-1','model_no' =>175],
            ['part_name' => 'WZJ8WZJ1121','model_no' =>175],
            ['part_name' => 'INNER','model_no' =>175],
            ['part_name' => 'HANDLE 837','model_no' =>3],
            ['part_name' => 'HANDLE 837','model_no' =>57],
            ['part_name' => 'COVER M64','model_no' =>57],
            ['part_name' => 'BODY P27','model_no' =>57],
            ['part_name' => 'HANDLE','model_no' =>57],
            ['part_name' => 'PLATE Q82 YELLOW','model_no' =>436],
            ['part_name' => 'PLATE Q82 YELLOW','model_no' =>374],
            ['part_name' => 'HANDLE 837','model_no' =>52],
            ['part_name' => 'COVER M64','model_no' =>11],
            ['part_name' => 'COVER M64','model_no' =>2],
            ['part_name' => 'HANDLE 837','model_no' =>2],
            ['part_name' => 'BODY N54','model_no' =>185],
            ['part_name' => 'HANDLE 837','model_no' =>26],
            ['part_name' => '221 BODY WHITE','model_no' =>470],
            ['part_name' => '015 TERMINAL SCREW','model_no' =>470],
            ['part_name' => '026 ROTATING PIECE WHITE','model_no' =>470],
            ['part_name' => '221 BODY WHITE','model_no' =>469],
            ['part_name' => 'OUTER BOX','model_no' =>6],
            ['part_name' => 'OUTER BOX','model_no' =>7],
            ['part_name' => 'OUTER BOX','model_no' =>452],
            ['part_name' => 'OUTER BOX','model_no' =>390],
            ['part_name' => 'COVER N61 ASSY','model_no' =>452],
            ['part_name' => 'COVER N61 ASSY','model_no' =>390],
            ['part_name' => 'SCREW 123','model_no' =>452],
            ['part_name' => 'SCREW 123','model_no' =>390],
            ['part_name' => 'OUTER BOX','model_no' =>438],
            ['part_name' => 'OUTER BOX','model_no' =>376],
            ['part_name' => 'OUTER BOX','model_no' =>449],
            ['part_name' => 'OUTER BOX','model_no' =>387],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>398],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>336],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>392],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>330],
            ['part_name' => 'OUTER BOX','model_no' =>187],
            ['part_name' => 'FUSED PLUG','model_no' =>187],
            ['part_name' => 'BODY 207','model_no' =>183],
            ['part_name' => 'SCREW 620','model_no' =>183],
            ['part_name' => 'OUTER BOX','model_no' =>183],
            ['part_name' => 'BODY R26','model_no' =>327],
            ['part_name' => 'COVER N61 ASSY','model_no' =>446],
            ['part_name' => 'COVER N61 ASSY','model_no' =>384],
            ['part_name' => 'BODY N 54 BLUE','model_no' =>194],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>397],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>335],
            ['part_name' => 'MODULLAR 63737','model_no' =>185],
            ['part_name' => 'SHUTTER H47W','model_no' =>185],
            ['part_name' => 'BODY BLOCK','model_no' =>391],
            ['part_name' => 'BODY BLOCK','model_no' =>329],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>399],
            ['part_name' => 'BODY BLOCK 1121','model_no' =>337],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>401],
            ['part_name' => 'BODY BLOCK 11217','model_no' =>339],
            ['part_name' => 'OUTER BOX','model_no' =>401],
            ['part_name' => 'OUTER BOX','model_no' =>339],
            ['part_name' => 'COVER PLATE Q82','model_no' =>421],
            ['part_name' => 'COVER PLATE Q82','model_no' =>359],
            ['part_name' => 'COVER N61 ASSY','model_no' =>421],
            ['part_name' => 'COVER N61 ASSY','model_no' =>359],
            ['part_name' => 'COVER PLATE Q78','model_no' =>432],
            ['part_name' => 'COVER PLATE Q78','model_no' =>370],
            ['part_name' => 'SCREW 620','model_no' =>432],
            ['part_name' => 'SCREW 620','model_no' =>370],
            ['part_name' => 'OUTER BOX','model_no' =>392],
            ['part_name' => 'OUTER BOX','model_no' =>330],
            ['part_name' => 'A60 TAB BLOCK','model_no' =>477],
            ['part_name' => 'COVER M64','model_no' =>40],
            ['part_name' => 'HANDLE 837','model_no' =>40],
            ['part_name' => 'NEON SWITCH C ASSY','model_no' =>40],
            ['part_name' => 'HANDLE LINE Q66 GRAY','model_no' =>18],
            ['part_name' => 'INNER BLANK WESJ 78069','model_no' =>212],
            ['part_name' => 'SENSOR','model_no' =>213],
            ['part_name' => '839 COIL SPRING','model_no' =>185],
            ['part_name' => 'NEON SWITCH C STYLE','model_no' =>50],
            ['part_name' => 'DIMMER WNJP 575283','model_no' =>274],
            ['part_name' => 'COVER M64','model_no' =>45],
            ['part_name' => 'PLATE T89','model_no' =>446],
            ['part_name' => 'PLATE T89','model_no' =>384],
            ['part_name' => '956 MOUNTING STRAP','model_no' =>433],
            ['part_name' => '956 MOUNTING STRAP','model_no' =>371],
            ['part_name' => '584','model_no' =>433],
            ['part_name' => '584','model_no' =>371],
            ['part_name' => '751','model_no' =>433],
            ['part_name' => '751','model_no' =>371],
            ['part_name' => 'BODY 207','model_no' =>433],
            ['part_name' => 'BODY 207','model_no' =>371],
            ['part_name' => 'T59','model_no' =>433],
            ['part_name' => 'T59','model_no' =>371],
            ['part_name' => 'SCREW 123','model_no' =>433],
            ['part_name' => 'SCREW 123','model_no' =>371],
            ['part_name' => 'MANUAL INSTRUCTION','model_no' =>213],
            ['part_name' => 'COVER 022 BLACK','model_no' =>478],
            ['part_name' => 'BODY 026 BLACK','model_no' =>478],
            ['part_name' => 'A62 TABLOCK','model_no' =>478],
            ['part_name' => 'INNER BOX WH 2013 BP','model_no' =>478],
            ['part_name' => 'B0DY A32 GREEY','model_no' =>186],
            ['part_name' => 'LUMP COVER 81 P','model_no' =>44],
            ['part_name' => 'COVER M64','model_no' =>44],
            ['part_name' => 'LUMP COVER X 83 P','model_no' =>46],
            ['part_name' => '379 HEXAGON NUT','model_no' =>472],
            ['part_name' => 'LUMP COVER X 83 P','model_no' =>45],
            ['part_name' => 'BODY BLOK 1121','model_no' =>396],
            ['part_name' => 'BODY BLOK 1121','model_no' =>334],
            ['part_name' => 'COVER M64','model_no' =>54],
            ['part_name' => 'LUMP COVER X81','model_no' =>54],
            ['part_name' => 'COVER M64','model_no' =>39],
            ['part_name' => 'HANDLE 837','model_no' =>39],
            ['part_name' => 'INNER','model_no' =>185],
            ['part_name' => 'BODY BLOCK H4768300A05','model_no' =>210],
            ['part_name' => 'LUMP COVER 81 P','model_no' =>43],
            ['part_name' => 'MANUAL INSTRUCTION','model_no' =>202],
            ['part_name' => 'COVER R26 GRAYY','model_no' =>193],
            ['part_name' => 'MODULAR 63737','model_no' =>193],
            ['part_name' => 'CAVER Q17 GRAY','model_no' =>192],
            ['part_name' => 'OUTER BOX WH2013PK','model_no' =>477],
            ['part_name' => 'INNER','model_no' =>194],
            ['part_name' => 'COVER R26 WHITE','model_no' =>185],
            ['part_name' => 'PLATE Y03 W','model_no' =>424],
            ['part_name' => 'PLATE Y03 W','model_no' =>362],
            ['part_name' => 'HANDLE 837','model_no' =>19],
            ['part_name' => 'NEON SWITCH C ASSY','model_no' =>26],
            ['part_name' => 'SCREW 018','model_no' =>478],
            ['part_name' => 'BODY 026W','model_no' =>476],
            ['part_name' => 'COVER 022 W','model_no' =>476],
            ['part_name' => 'OUTER BOX','model_no' =>476],
            ['part_name' => 'INNER BOX','model_no' =>476],
            ['part_name' => '148 SOCKET CONTACT BLOCK','model_no' =>476],
            ['part_name' => '018 PANHEAD TAPPING SCREW','model_no' =>476],
            ['part_name' => 'HANDLE 837','model_no' =>28],
            ['part_name' => 'HANDLE 837','model_no' =>27],
            ['part_name' => 'NEON SWITCH C STYLE','model_no' =>48],
            ['part_name' => 'COVER M64','model_no' =>37],
            ['part_name' => 'COVER N61ASSY','model_no' =>436],
            ['part_name' => 'COVER N61ASSY','model_no' =>374],
            ['part_name' => 'COVER N61ASSY','model_no' =>448],
            ['part_name' => 'COVER N61ASSY','model_no' =>386],
            ['part_name' => 'OUTER BOX','model_no' =>398],
            ['part_name' => 'OUTER BOX','model_no' =>336],
            ['part_name' => 'TAB BLOCK A42','model_no' =>475],
            ['part_name' => 'SOCKET CONTACK BLOCK 18','model_no' =>473],
            ['part_name' => 'PLATE T89 SILVER','model_no' =>447],
            ['part_name' => 'PLATE T89 SILVER','model_no' =>385],
            ['part_name' => 'COVER N61 GREY','model_no' =>447],
            ['part_name' => 'COVER N61 GREY','model_no' =>385],
            ['part_name' => 'TAB BLOCK A40','model_no' =>474],
            ['part_name' => 'CAVER Q17 W','model_no' =>194],
            ['part_name' => 'BODY BLOCK 1131-7','model_no' =>439],
            ['part_name' => 'BODY BLOCK 1131-7','model_no' =>377],
            ['part_name' => 'COVER N61 GREY','model_no' =>439],
            ['part_name' => 'COVER N61 GREY','model_no' =>377],
            ['part_name' => 'PLATE Q78 BROWN METALIC','model_no' =>439],
            ['part_name' => 'PLATE Q78 BROWN METALIC','model_no' =>377],
            ['part_name' => 'DUMF3200J','model_no' =>182],
            ['part_name' => 'OUTER BOX','model_no' =>443],
            ['part_name' => 'OUTER BOX','model_no' =>381],
            ['part_name' => 'SCREW 620','model_no' =>434],
            ['part_name' => 'SCREW 620','model_no' =>372],
            ['part_name' => 'OUTER BOX','model_no' =>434],
            ['part_name' => 'OUTER BOX','model_no' =>372],
            ['part_name' => 'COVER PLATE Q82 SILVER METALIC','model_no' =>437],
            ['part_name' => 'COVER PLATE Q82 SILVER METALIC','model_no' =>375],
            ['part_name' => 'SCREW 620','model_no' =>447],
            ['part_name' => 'SCREW 620','model_no' =>385],
            ['part_name' => 'OUTER BOX','model_no' =>447],
            ['part_name' => 'OUTER BOX','model_no' =>385],
            ['part_name' => 'BODY 207','model_no' =>452],
            ['part_name' => 'BODY 207','model_no' =>390],
            ['part_name' => 'BODY BLOCK STYLE 1121-7','model_no' =>403],
            ['part_name' => 'BODY BLOCK STYLE 1121-7','model_no' =>341],
            ['part_name' => 'OUTER BOX','model_no' =>403],
            ['part_name' => 'OUTER BOX','model_no' =>341],
            ['part_name' => 'SCREW 620','model_no' =>430],
            ['part_name' => 'SCREW 620','model_no' =>368],
            ['part_name' => 'OUTER BOX','model_no' =>1],
            ['part_name' => 'INNER BOX','model_no' =>1],
            ['part_name' => 'BODY P27','model_no' =>1],
            ['part_name' => 'COVER M64','model_no' =>14],
            ['part_name' => 'OUTER BOX','model_no' =>426],
            ['part_name' => 'OUTER BOX','model_no' =>364],
            ['part_name' => 'BODY 208','model_no' =>419],
            ['part_name' => 'BODY 208','model_no' =>357],
            ['part_name' => 'OUTER BOX','model_no' =>419],
            ['part_name' => 'OUTER BOX','model_no' =>357],
            ['part_name' => 'COVER M64','model_no' =>19],
            ['part_name' => 'INNER BOX WH4021W','model_no' =>469],
            ['part_name' => 'HANDLE BLOCK Q66 GRAY METALIC','model_no' =>15],
            ['part_name' => 'BLANK CHIP','model_no' =>176],
            ['part_name' => 'SHUTTER H 47','model_no' =>194],
            ['part_name' => 'HANDLE 543 BROWN','model_no' =>22],
            ['part_name' => 'COVER M64','model_no' =>29],
            ['part_name' => 'HANDLE 837','model_no' =>29],
            ['part_name' => 'COVER PLATE Q82 GREEN','model_no' =>423],
            ['part_name' => 'COVER PLATE Q82 GREEN','model_no' =>361],
            ['part_name' => 'COVER PLATE Q82 BLUE','model_no' =>428],
            ['part_name' => 'COVER PLATE Q82 BLUE','model_no' =>366],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>439],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>377],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>445],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>383],
            ['part_name' => 'COVER N61ASSY','model_no' =>445],
            ['part_name' => 'COVER N61ASSY','model_no' =>383],
            ['part_name' => 'COVER PLATE Q82 YELLOW','model_no' =>445],
            ['part_name' => 'COVER PLATE Q82 YELLOW','model_no' =>383],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>420],
            ['part_name' => 'BODY BLOCK 11317','model_no' =>358],
            ['part_name' => '148 SOCKET CONTACT BLOCK','model_no' =>478],
            ['part_name' => 'DU59JTK1','model_no' =>176],
            ['part_name' => 'OUTER BOX','model_no' =>472],
            ['part_name' => 'INNER BOX','model_no' =>470],
            ['part_name' => 'COVER M64','model_no' =>43],
            ['part_name' => 'COVER M64','model_no' =>9],
            ['part_name' => 'HANDLE 837','model_no' =>9],
            ['part_name' => 'BODY BLOCK STYLE 1121-7','model_no' =>395],
            ['part_name' => 'BODY BLOCK STYLE 1121-7','model_no' =>333],
            ['part_name' => 'HANDLE 837','model_no' =>38],
            ['part_name' => 'HANDLE 837','model_no' =>38],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>421],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>359],
            ['part_name' => 'COVER M64','model_no' =>41],
            ['part_name' => 'NEON SWITCH C STYLE','model_no' =>49],
            ['part_name' => 'LUMP COVER X 83 P','model_no' =>49],
            ['part_name' => 'LUMP COVER 81','model_no' =>47],
            ['part_name' => 'LUMP COVER 81','model_no' =>48],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>405],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>343],
            ['part_name' => 'OUTER BOX','model_no' =>405],
            ['part_name' => 'OUTER BOX','model_no' =>343],
            ['part_name' => 'COVER PLATE Y05 W','model_no' =>405],
            ['part_name' => 'COVER PLATE Y05 W','model_no' =>343],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>406],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>344],
            ['part_name' => 'OUTER BOX','model_no' =>406],
            ['part_name' => 'OUTER BOX','model_no' =>344],
            ['part_name' => 'COVER PLATE Y04 W','model_no' =>406],
            ['part_name' => 'COVER PLATE Y04 W','model_no' =>344],
            ['part_name' => 'BODY R 25 ASSY','model_no' =>211],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>430],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>368],
            ['part_name' => 'COVER PLATE Q82','model_no' =>420],
            ['part_name' => 'COVER PLATE Q82','model_no' =>358],
            ['part_name' => 'COVER W55','model_no' =>420],
            ['part_name' => 'COVER W55','model_no' =>358],
            ['part_name' => 'PLATE T89','model_no' =>425],
            ['part_name' => 'PLATE T89','model_no' =>363],
            ['part_name' => 'WZJ 81121','model_no' =>174],
            ['part_name' => 'OUTER BOX','model_no' =>174],
            ['part_name' => 'HANDLE 547','model_no' =>14],
            ['part_name' => 'HANDLE 837','model_no' =>56],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>450],
            ['part_name' => 'BODY BLOCK 1121-7','model_no' =>388],
            ['part_name' => 'COVER N61 GRAY','model_no' =>450],
            ['part_name' => 'COVER N61 GRAY','model_no' =>388],
            ['part_name' => 'COVER PLATE T89 BLUE METALIC','model_no' =>450],
            ['part_name' => 'COVER PLATE T89 BLUE METALIC','model_no' =>388],
            ['part_name' => 'SCREW 620','model_no' =>450],
            ['part_name' => 'SCREW 620','model_no' =>388],
            ['part_name' => 'HANDLE LINE Q66','model_no' =>13],
            ['part_name' => 'HANDLE BLOCK 543 BROWN METALIC','model_no' =>17],
            ['part_name' => 'INNER','model_no' =>210],
            ['part_name' => 'BODY BLOCK H4768300A06','model_no' =>210],
            ['part_name' => 'COVER M64','model_no' =>51],
            ['part_name' => 'SCREW 620','model_no' =>425],
            ['part_name' => 'SCREW 620','model_no' =>363],
            ['part_name' => 'WEJ 3020','model_no' =>177],
            ['part_name' => 'WEJ 3020','model_no' =>176],
            ['part_name' => 'HANDLE 543','model_no' =>13],
        ]);
    }
}
