<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product')->insert([
            ['model_no' => 'WESJ5571',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 10.92 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5571MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 10.92 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5571B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 9.82 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5571',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 12.15 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5581',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 9.80 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5521',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5511',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.93 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5571',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 14.13 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5561',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 22.97 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5551',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 22.97 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5581',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5581MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 10.11 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532MYX',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532MYZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532MAE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532MDZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5532MRE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542MYX',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542MYZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542MAE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542MDZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5542MRE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 12.15 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572MYX',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572MYZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572MAE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572MDZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5572MRE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582MYX',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582MYZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582MAE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582MDZ',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5582MRE',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5532',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5522',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5512',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5572',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5562',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5552',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5932',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5932MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5942',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 18.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5942MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 18.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5572',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5572MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5582',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 18.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5582MWS',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 18.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5572B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5581B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 17.09 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5582B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 18.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5932B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 13.13 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5942B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 14.85 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ5941B',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 14.85 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ5531',  'line' => 'Manual Switch' , 'section' => 'ASSY WD', 'time' => 12.00 ,'std_mp' => 3 ],
            ['model_no' => 'WCJP51181',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 25.46 ,'std_mp' => 4 ],
            ['model_no' => 'WCJP52181',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 29.60 ,'std_mp' => 4 ],
            ['model_no' => 'WCJP1131',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 28.17 ,'std_mp' => 4 ],
            ['model_no' => 'WCJP2501',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 38.91 ,'std_mp' => 4 ],
            ['model_no' => 'WCJP2164',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 42.19 ,'std_mp' => 4 ],
            ['model_no' => 'WCJP2488',  'line' => 'Flasimo' , 'section' => 'ASSY WD', 'time' => 34.28 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5011-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5012-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5021-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5022-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5031-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5032-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5303-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ1610-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ1211-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ3010-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ3118-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ3217-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5511-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ5911-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'WABJ8010-N',  'line' => 'BS Type' , 'section' => 'ASSY WD', 'time' => 39.54 ,'std_mp' => 4 ],
            ['model_no' => 'DU5913JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 86.77 ,'std_mp' => 2 ],
            ['model_no' => 'DU5915JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 83.78 ,'std_mp' => 2 ],
            ['model_no' => 'DU5919JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 83.78 ,'std_mp' => 2 ],
            ['model_no' => 'DU6933JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 83.78 ,'std_mp' => 2 ],
            ['model_no' => 'DU6935JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 83.78 ,'std_mp' => 2 ],
            ['model_no' => 'DU6955JTK1',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 100.00 ,'std_mp' => 2 ],
            ['model_no' => 'DUMF3230J',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 95.28 ,'std_mp' => 2 ],
            ['model_no' => 'DUMF3233J',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 138.84 ,'std_mp' => 2 ],
            ['model_no' => 'DUMF3200J',  'line' => 'POP UP (DU)' , 'section' => 'ASSY WD', 'time' => 138.84 ,'std_mp' => 2 ],
            ['model_no' => 'WKJ1131',  'line' => 'WKJ' , 'section' => 'ASSY WD', 'time' => 18.58 ,'std_mp' => 1 ],
            ['model_no' => 'WNJ3700',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 16.41 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ24886',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 12.12 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3020H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 15.65 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ9111W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 15.28 ,'std_mp' => 3 ],
            ['model_no' => 'WBJ6010W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 10.31 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3020',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 8.18 ,'std_mp' => 3 ],
            ['model_no' => 'EGG331',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 19.56 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57515H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 11.96 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ2488H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 6.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ24886H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 5.45 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ2488',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 12.58 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6009',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 19.85 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7152CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 13.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5262CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 23.45 ,'std_mp' => 3 ],
            ['model_no' => 'WNJP575213',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 25.97 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6015',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP51552S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP52562S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'EBG888',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 27.97 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ3020',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 27.41 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57625CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 25.00 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6012',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ54017',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 18.38 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57518',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEF1172W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'NRJ3170W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 12.67 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57515',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 17.15 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069MWS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 28.27 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 28.27 ,'std_mp' => 3 ],
            ['model_no' => 'WTKJ2311',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 19.64 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP53572S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78049CW',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 28.27 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069CW',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 28.27 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ7823W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 3.87 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5162CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 183.75 ,'std_mp' => 3 ],
            ['model_no' => 'AM311W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'AMS313W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'AMS312W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WIS311-191W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WSJ3900P',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'SEC211MWS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'SES312MWS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57518H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WSJ3001P',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7252CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 12.67 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7101W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7001W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEF1172H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 23.71 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ3710K',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WNTJ15649W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7352CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 183.75 ,'std_mp' => 3 ],
            ['model_no' => 'NRJ3160W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78029AS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6806',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3032R',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WZJ1781W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6891',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6804',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6203',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ6206',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7002W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7003W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7102W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7103W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7104W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7122W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7006W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7101MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7101MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 31.96 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7102MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7102MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7103MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7103MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7104MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7104MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WZJ1781MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WZJ1781MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7001MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7001MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7002MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7002MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7003MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7003MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7006MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTFJ7006MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEHJ6806W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ5401H7',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 18.38 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ9986',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 81.67 ,'std_mp' => 3 ],
            ['model_no' => 'WNJP575152',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WNJP575253',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 33.41 ,'std_mp' => 3 ],
            ['model_no' => 'WNJP575283',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 33.41 ,'std_mp' => 3 ],
            ['model_no' => 'WBJ1214',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 25.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5362CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 183.75 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57628CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 183.75 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5401CH',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 183.75 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7152MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 13.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7152MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 13.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7252MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7252MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7352MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ7352MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57625MYE',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57625MYX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57628MYEK',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ57628MYXK',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 408.33 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5631W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 245.00 ,'std_mp' => 3 ],
            ['model_no' => 'WNTJ15649H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WTCJ5631H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'NRJ3160H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'NRJ3170H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 12.67 ,'std_mp' => 3 ],
            ['model_no' => 'WNJ3022H',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ575151',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ575181',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 0.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3032W',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3032G',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ1081B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ2164B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ24886B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ2488B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ2501B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ3020B',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57813B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ57816B1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJ1781S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJ6503S1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJ6506S1',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 24.50 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP54562S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP55582S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WTEJP56572S',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WEJ30029TG',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 105.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78019B',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78029B',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78049B',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069B',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 28.27 ,'std_mp' => 3 ],
            ['model_no' => 'WFAJ4452G',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 122.50 ,'std_mp' => 3 ],
            ['model_no' => 'WFAJ5293G',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 49.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78019CW',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78029CW',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 26.25 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78019CGX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78029CGX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78049CGX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069CGX',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78019AS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78049AS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJ78069AS',  'line' => 'Outline' , 'section' => 'ASSY WD', 'time' => 2.83 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222W',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222MWS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223MWS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223W',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233MWS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233W',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212W',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212MWS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212B',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121B',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 12.18 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222B',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223B',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233B',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121CW',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212CW',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222CW',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223CW',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233CW',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121CGX',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212CGX',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222CGX',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223CGX',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233CGX',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121AS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212AS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222AS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223AS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233AS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121MWS',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WEJP113127',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP112127',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121F7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TG7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WESJP1121W',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 12.18 ,'std_mp' => 3 ],
            ['model_no' => 'WEJP113227',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MYX7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MYZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TL7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TN7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MAE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MDZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MRE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TG7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TL7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TN7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212F7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MYX7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MYZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MAE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MDZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MRE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TG7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TL7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TN7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222F7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP112227',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MYX7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MYZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MAE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MDZ7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MRE7',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJ11217H',  'line' => 'Manual Consent 2' , 'section' => 'ASSY WD', 'time' => 2.00 ,'std_mp' => 4 ],
            ['model_no' => 'WESJP11222W',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222MWS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223MWS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223W',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233MWS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233W',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212W',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212MWS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212B',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 17.00 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121B',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 12.18 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222B',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223B',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233B',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121CW',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212CW',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222CW',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223CW',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233CW',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121CGX',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212CGX',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222CGX',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223CGX',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233CGX',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121AS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11212AS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11222AS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11223AS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP11233AS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WESJP1121MWS',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 19.12 ,'std_mp' => 3 ],
            ['model_no' => 'WEJP113127',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP112127',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121F7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TG7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WESJP1121W',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 12.18 ,'std_mp' => 3 ],
            ['model_no' => 'WEJP113227',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MYX7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MYZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TL7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121TN7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MAE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MDZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP1121MRE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TG7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TL7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212TN7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212F7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MYX7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MYZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MAE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MDZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11212MRE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 6.75 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TG7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TL7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222TN7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222F7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP112227',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MYX7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MYZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MAE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MDZ7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJP11222MRE7',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 8.03 ,'std_mp' => 4 ],
            ['model_no' => 'WEJ11217H',  'line' => 'Manual Consent 3' , 'section' => 'ASSY WD', 'time' => 2.00 ,'std_mp' => 4 ],
            ['model_no' => '73500856004',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.07 ,'std_mp' => 1 ],
            ['model_no' => '73500856005T',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.07 ,'std_mp' => 1 ],
            ['model_no' => '73500856004V',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.09 ,'std_mp' => 1 ],
            ['model_no' => '73501156003T',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.18 ,'std_mp' => 1 ],
            ['model_no' => '73501156004T',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.15 ,'std_mp' => 1 ],
            ['model_no' => '73501156003V',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.18 ,'std_mp' => 1 ],
            ['model_no' => '73502056002',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.18 ,'std_mp' => 1 ],
            ['model_no' => '73502056003T',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.15 ,'std_mp' => 1 ],
            ['model_no' => '73502056002V',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.15 ,'std_mp' => 1 ],
            ['model_no' => '73501356004',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.18 ,'std_mp' => 1 ],
            ['model_no' => '73501956002',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.14 ,'std_mp' => 1 ],
            ['model_no' => '73500856004J',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.09 ,'std_mp' => 1 ],
            ['model_no' => '73501156003J',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.18 ,'std_mp' => 1 ],
            ['model_no' => '73502056003J',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.15 ,'std_mp' => 1 ],
            ['model_no' => '73500856005V',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.07 ,'std_mp' => 1 ],
            ['model_no' => '73501156004V',  'line' => 'Hikishime' , 'section' => 'TAP CAP', 'time' => 0.15 ,'std_mp' => 1 ],
            ['model_no' => 'WH4021W',  'line' => 'Snap Cap' , 'section' => 'TAP CAP', 'time' => 6.21 ,'std_mp' => 4 ],
            ['model_no' => 'WH4021WP',  'line' => 'Snap Cap' , 'section' => 'TAP CAP', 'time' => 10.35 ,'std_mp' => 4 ],
            ['model_no' => 'WH4021B',  'line' => 'Snap Cap' , 'section' => 'TAP CAP', 'time' => 6.21 ,'std_mp' => 4 ],
            ['model_no' => 'WH4021BP',  'line' => 'Snap Cap' , 'section' => 'TAP CAP', 'time' => 10.29 ,'std_mp' => 4 ],
            ['model_no' => 'WH2012',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 10.89 ,'std_mp' => 3 ],
            ['model_no' => 'WH2012PK',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 13.25 ,'std_mp' => 3 ],
            ['model_no' => 'WH2012BP',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 13.25 ,'std_mp' => 3 ],
            ['model_no' => 'WH2013',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 8.85 ,'std_mp' => 3 ],
            ['model_no' => 'WH2013PK',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 9.25 ,'std_mp' => 3 ],
            ['model_no' => 'WH2013BP',  'line' => 'Tritap- Sankaku' , 'section' => 'TAP CAP', 'time' => 9.25 ,'std_mp' => 3 ],
            ['model_no' => 'HB142500001',  'line' => 'Hikishime' , 'section' => 'BK COIL', 'time' => 17.50 ,'std_mp' => 13 ],
            ['model_no' => 'HB142600001',  'line' => 'Hikishime' , 'section' => 'BK COIL', 'time' => 17.50 ,'std_mp' => 13 ],
            ['model_no' => 'HB142700001',  'line' => 'Hikishime' , 'section' => 'BK COIL', 'time' => 17.50 ,'std_mp' => 13 ],
            ['model_no' => 'HB142800001',  'line' => 'Hikishime' , 'section' => 'BK COIL', 'time' => 17.50 ,'std_mp' => 13 ],
            ['model_no' => 'HB147700001',  'line' => 'Hikishime' , 'section' => 'BK COIL', 'time' => 17.50 ,'std_mp' => 13 ],
        ]);
    }
}