<html>

<head>
    <title>Data PWK</title>
    <style>
    table,
    th,
    td {
        border: 1px solid black;
        border-collapse: collapse;
        white-space: nowrap;
    }
    </style>
</head>
<body>
<table>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            FORM PERMINTAAN PEMERIKSAAN DAN PENYERAHAN FINISH GOOD
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Petugas PC</td>
        <td></td>
        <td>Petugas Produksi</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>
            Tanggal Produksi: {{date('Y - m - d', strtotime($tanggal))}}
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>No</td>
        <td>Tipe Produk</td>
        <td>No Lot</td>
        <td>Shift</td>
        <td>Packing</td>
        <td>Total Box</td>
        <td>Total Qty</td>
        <td>Keterangan</td>
        <td></td>
    </tr>
    @foreach ($domestic as $dom)
    <tr>
        <td></td>
        <td>{{$i++}}</td>
        <td>{{$dom->model_no}}</td>
        <td>{{date('Ymd', strtotime($dom->lotno))}}</td>
        <td>{{$dom->shift}}</td>
        <td>{{$dom->packing}}</td>
        <td>{{$dom->total_box}}</td>
        <td>{{$dom->total_qty}}</td>
        <td>{{$dom->remark}}</td>
        <td></td>
    </tr>
    @endforeach
    
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>Export</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    @foreach ($export as $exp)
    <tr>
        <td></td>
        <td>{{$i++}}</td>
        <td>{{$exp->model_no}}</td>
        <td>{{date('Ymd', strtotime($exp->lotno))}}</td>
        <td>{{$exp->shift}}</td>
        <td>{{$exp->packing}}</td>
        <td>{{$exp->total_box}}</td>
        <td>{{$exp->total_qty}}</td>
        <td>{{$exp->remark}}</td>
        <td></td>
    </tr>
    @endforeach
    @for($n = $i ; $n < 31; $n++)
    <tr>
        <td></td>
        <td>{{$n}}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    @endfor
    <tr>
        <td></td>
        <td>
            Catatan : 
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>
            1. Pengecekan hasil transfers produksi shift 1 dilakukan oleh Group Leader Shift 1
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>
            2. Pengecekan hasil transfers produksi shift 2 dilakukan oleh Line Leader Shift 3
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>
            3. Pengecekan hasil transfers produksi shift 3 dilakukan oleh Group Leader Shift 1
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>
            4. Setelah petugas produksi selesai input hasil produksi, form diserahkan kepada PC
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td>
        PT. Panasonic Gobel Life Solutions Manufacturing Indonesia
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
</body>